AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  URL Shortener com Spring + Lambda + API Gateway + DynamoDB.

Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  UrlShortenerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  UrlShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: url-shortener-app-fn
      CodeUri: .
      Handler: com.br.shortener.url.infrastructure.handlers.aws.lambda.StreamLambdaHandler::handleRequest
      Runtime: java21
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlMappingsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlMappingsTable
      Events:
        ShortenUrl:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /api/shorten
            Method: post
        RedirectUrl:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /api/{shortCode}
            Method: get
        InfoUrl:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /api/{shortCode}/info
            Method: get


  UrlMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlMappings
      AttributeDefinitions:
        - AttributeName: shortCode
          AttributeType: S
      KeySchema:
        - AttributeName: shortCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expirationTime
        Enabled: true

Outputs:
  ApiUrl:
    Description: "URL base do API Gateway para a aplicação"
    Value: !Sub "https://${UrlShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"